sudo: required
language: go
go:
  - 1.11.x
addons:
  apt:
    packages:
    - git
    - make
    - curl

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install:
- make init
- make go/deps-build
- make go/deps-dev

script:
- make go/deps
- make go/test
- make go/lint
- make go/build-all
- make test
- ls -l release/

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: "release/*"
  skip_cleanup: true
  on:
    tags: true

